# anagrams.data
"""Data package: bundled static assets used at runtime.

Contents
--------
sigmap.json
    A prebuilt JSON object mapping each word signature (sorted uppercase
    letters) to a list of matching words.  Generated by
    ``anagrams.build_sigmap`` from ``setup/words.txt``.
"""
